openapi: 3.0.1
info:
  title: CipheRing Backend APIs
  description: Backend APIs for CipheRing by Sqewes
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /health:
    get:
      summary: Health Check
      description: Returns a simple OK string
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Application is running
          content:
            text/plain:
              schema:
                type: string
                example: OK
        '500':
          description: Server error
