openapi: 3.0.1
info:
  title: CipheRing Backend APIs
  description: Backend APIs for CipheRing by Sqewes
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /health:
    get:
      summary: Health Check
      description: Returns a simple OK string
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Application is running
          content:
            text/plain:
              schema:
                type: string
                example: OK
        '500':
          description: Server error
  /user/register:
    post:
      summary: Register a new user
      description: Register a new user
      operationId: register
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegistrationResponse'
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - Phone number already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    UserRegistrationRequest:
      type: object
      required:
        - phoneNumber
        - userName
      properties:
        phoneNumber:
          type: string
          description: User's phone number
          example: "9876543210"
          pattern: "^[0-9]{10}$"
        userName:
          type: string
          description: User's full name
          example: "john doe"
          minLength: 1
          maxLength: 100
    UserRegistrationResponse:
      type: object
      properties:
        message:
          type: string
          example: "User registered successfully"
        userId:
          type: string
          example: "user123"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error message"
